default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues:  "transcribe"
      threads: 1  # Ensures only one job runs at a time for this queue
      polling_interval: 5
    - queues: "default"
      threads: 3
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 1) %>
      polling_interval: 5
    - queues: "mailers"
      threads: 3
      processes: <%= ENV.fetch("JOB_CONCURRENCY", 1) %>
      polling_interval: 5

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
